# ===========================
#  Libra Worker Docker Image
# ===========================
FROM node:20-bullseye-slim

# Install LibreOffice and utilities
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libreoffice-core \
      libreoffice-writer \
      libreoffice-impress \
      libreoffice-common \
      libreoffice-java-common \
      libreoffice-calc \
      libreoffice-draw \
      poppler-utils \
      imagemagick \
      qpdf \
      ca-certificates \
      wget \
      fonts-dejavu-core \
      gzip \
      unzip \
      ttf-mscorefonts-installer --no-install-recommends || true && \
    rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m -s /bin/bash appuser
WORKDIR /home/appuser
USER appuser

# Copy package.json and lock file generated by workflow
COPY --chown=appuser:appuser package.json pnpm-lock.yaml ./

# Install dependencies using pnpm
RUN corepack enable \
 && corepack prepare pnpm@latest --activate \
 && pnpm install --prod --frozen-lockfile

# Copy application source
COPY --chown=appuser:appuser . .

# Environment setup
ENV NODE_ENV=production
ENV TMPDIR=/home/appuser/tmp
RUN mkdir -p /home/appuser/tmp && chmod 700 /home/appuser/tmp

# Healthcheck to verify LibreOffice availability
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD soffice --version | grep "LibreOffice" || exit 1

# Default command
CMD ["node", "worker.js"]
