# ===========================
#  Libra Worker Docker Image
# ===========================
FROM node:20-bullseye-slim

# Install LibreOffice and utilities (avoid ttf-mscorefonts-installer)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libreoffice-core \
      libreoffice-writer \
      libreoffice-impress \
      libreoffice-common \
      libreoffice-java-common \
      libreoffice-calc \
      libreoffice-draw \
      poppler-utils \
      imagemagick \
      qpdf \
      ca-certificates \
      wget \
      fonts-dejavu-core \
      gzip \
      unzip \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user (we will install deps as root first)
RUN useradd -m -s /bin/bash appuser

WORKDIR /home/appuser

# Copy dependency manifest files (these are generated by your CI before docker build)
COPY package.json pnpm-lock.yaml ./

# Install pnpm and production dependencies as root (required to write to /usr/local)
# Try corepack first; fall back to npm global install if prepare fails.
RUN set -eux; \
    corepack enable || echo "corepack enable failed, continuing"; \
    corepack prepare pnpm@latest --activate 2>/dev/null || echo "corepack prepare failed, falling back to npm global install"; \
    if ! command -v pnpm >/dev/null 2>&1; then \
      npm install -g pnpm@latest; \
    fi; \
    pnpm -v; \
    pnpm install --prod --frozen-lockfile

# Copy the rest of the app source and adjust ownership
COPY . .
RUN chown -R appuser:appuser /home/appuser

# Switch to non-root user
USER appuser

# Environment setup
ENV NODE_ENV=production
ENV TMPDIR=/home/appuser/tmp
RUN mkdir -p /home/appuser/tmp && chmod 700 /home/appuser/tmp

# Healthcheck to verify LibreOffice availability (runs as non-root)
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD soffice --version | grep "LibreOffice" || exit 1

# Start worker
CMD ["node", "worker.js"]
